version: '3'
services:
  db:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      - db
    ports:
      - "3312:80"
